enum error_codes {
	SUCCESS = 0,
	NOT_INITIALISED = 1,

	PWM_DRV_NOT_READY = 2,
	GPIO_OUT_DIR_CNTRL_NOT_READY = 3,
	GPIO_IN_ENC_NOT_READY = 4,
	GPIO_OUT_BOOT_NOT_READY = 5,
	UNABLE_TO_SET_PWM = 6,

	DESIRED_VALUE_TO_HIGH = 7,

	UNABLE_TO_SET_GPIO = 8,

	UNSUPPORTED_FUNCTION_IN_CURRENT_MODE = 9,
	VALUE_CONVERSION_ERROR = 10,

	ERROR_CODE_FROM_ERRNO_DURING_NVS_WRITE = 11,
	NOTHING_WRITTEN_DURING_NVS_WRITE = 12,
	ERROR_CODE_FROM_ERRNO_DURING_NVS_READ = 13,
	NOTHING_READ_DURING_NVS_READ = 14,

	TOO_MANY_TEMPLATES_DEFINED = 15,

	COULDNT_FIND_TEMPLATE = 16,
	EMPTY_TEMPLATE_LIST = 17
};

// TODO - Add ERR before all error codes